### PR TITLE
Folders for Cloudmask, Uno and Stemdl

### PR DESCRIPTION
**Pull request by juripapay**
Uploaded three folders to "juribranch"

### CODE REVIEW

**Review by laszewsk — APPROVED** [review]
Please use empty lines after a markdown hash so advanced editors such as emacs can do block formating easier

**Comment by morphine00** [comment]
recheck

**Comment by juri** [comment]
Hey, I'm getting emails from this repo I know nothing about. You seem to be using the wrong user name in the messages.

**Comment by morphine00** [comment]
> Hey, I'm getting emails from this repo I know nothing about. You seem to be using the wrong user name in the messages.

@juri We're sorry, our CLA signing bot is having a bit of an issue. Please disregard any notifications in the meantime.

**Pull request closed without merging**
